weakness = [
    {'type': 'neutral',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 1,
         'water': 1,
         'fire': 1,
         'nature': 1,
         'electric': 1,
         'mental': 2,
         'digital': 1,
         'melee': 1,
         'crystal': 1,
         'toxic': 1,
     }
     },
    {'type': 'wind',
     'weaknesses': {
         'neutral': 1,
         'wind': 0.5,
         'earth': 0.5,
         'water': 1,
         'fire': 1,
         'nature': 1,
         'electric': 2,
         'mental': 1,
         'digital': 1,
         'melee': 1,
         'crystal': 1,
         'toxic': 1,
     }
     },
    {'type': 'earth',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 1,
         'water': 2,
         'fire': 0.5,
         'nature': 2,
         'electric': 0.5,
         'mental': 1,
         'digital': 1,
         'melee': 2,
         'crystal': 0.5,
         'toxic': 0.5,
     }
     },
    {'type': 'water',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 0.5,
         'water': 0.5,
         'fire': 0.5,
         'nature': 2,
         'electric': 2,
         'mental': 1,
         'digital': 1,
         'melee': 1,
         'crystal': 1,
         'toxic': 2, }
     },
    {'type': 'fire',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 2,
         'water': 2,
         'fire': 0.5,
         'nature': 0.5,
         'electric': 1,
         'mental': 1,
         'digital': 1,
         'melee': 1,
         'crystal': 0.5,
         'toxic': 1, }
     },
    {'type': 'nature',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 0.5,
         'water': 0.5,
         'fire': 2,
         'nature': 0.5,
         'electric': 0.5,
         'mental': 1,
         'digital': 1,
         'melee': 1,
         'crystal': 1,
         'toxic': 2, }
     },
    {'type': 'electric',
     'weaknesses': {
         'neutral': 1,
         'wind': 0.5,
         'earth': 2,
         'water': 1,
         'fire': 1,
         'nature': 1,
         'electric': 0.5,
         'mental': 1,
         'digital': 1,
         'melee': 1,
         'crystal': 2,
         'toxic': 1, }
     },
    {'type': 'mental',
     'weaknesses': {
         'neutral': 0.5,
         'wind': 1,
         'earth': 1,
         'water': 1,
         'fire': 1,
         'nature': 1,
         'electric': 2,
         'mental': 1,
         'digital': 2,
         'melee': 0.5,
         'crystal': 2,
         'toxic': 1, }
     },
    {'type': 'digital',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 1,
         'water': 2,
         'fire': 1,
         'nature': 1,
         'electric': 2,
         'mental': 1,
         'digital': 2,
         'melee': 1,
         'crystal': 1,
         'toxic': 0.5, }
     },
    {'type': 'melee',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 1,
         'water': 1,
         'fire': 1,
         'nature': 1,
         'electric': 1,
         'mental': 2,
         'digital': 2,
         'melee': 0.5,
         'crystal': 1,
         'toxic': 1, }
     },
    {'type': 'crystal',
     'weaknesses': {
         'neutral': 1,
         'wind': 1,
         'earth': 2,
         'water': 1,
         'fire': 2,
         'nature': 1,
         'electric': 0.5,
         'mental': 0.5,
         'digital': 1,
         'melee': 2,
         'crystal': 1,
         'toxic': 0.5, }
     },
    {'type': 'toxic',
     'weaknesses': {
         'neutral': 1,
         'wind': 2,
         'earth': 1,
         'water': 0.5,
         'fire': 1,
         'nature': 0.5,
         'electric': 1,
         'mental': 1,
         'digital': 1,
         'melee': 1,
         'crystal': 1,
         'toxic': 0.5, }
     },
]
